package idl;


/**
* idl/PoliceStation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./policestation.idl
* Tuesday, November 19, 2013 10:50:19 AM EST
*/

public interface PoliceStation extends PoliceStationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PoliceStation
