package idl;


/**
* idl/PoliceStationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./policestation.idl
* Tuesday, November 19, 2013 10:50:19 AM EST
*/

abstract public class PoliceStationHelper
{
  private static String  _id = "IDL:idl/PoliceStation:1.0";

  public static void insert (org.omg.CORBA.Any a, idl.PoliceStation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static idl.PoliceStation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (idl.PoliceStationHelper.id (), "PoliceStation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static idl.PoliceStation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PoliceStationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, idl.PoliceStation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static idl.PoliceStation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof idl.PoliceStation)
      return (idl.PoliceStation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      idl._PoliceStationStub stub = new idl._PoliceStationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static idl.PoliceStation unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof idl.PoliceStation)
      return (idl.PoliceStation)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      idl._PoliceStationStub stub = new idl._PoliceStationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
